"""Compatibility shim: chapter titles are now generated, not patched in.

Chapter titles used to be added to _quarto.yml, index.qmd and the chapter pages
by rewriting those files after tools/0_generate_site.py had produced them.  That
step was skipped by .github/workflows/publish.yml, so the published site lost
the titles, and it could not be adapted to the per-language subtrees.

tools/0_generate_site.py now writes the titles directly (see
CHAPTER_TITLES_ROMAN) and also produces data/chapter_titles.json, so nothing is
left to patch.  This file stays only so that run.bat and any existing habit keep
working; it can be deleted together with its step in run.bat.
"""


def main():
    print("Chapter titles are generated by tools/0_generate_site.py; nothing to patch.")


if __name__ == "__main__":
    main()
